version: '3'
services:
  burninup-frontend:
    image: burninup-frontend:0.1
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    expose:
      - "3000"
    tty: true

  burninup-backend:
    image: burninup-backend:0.1
    environment:
      PORT: 5000
    ports:
      - 5000:5000
    expose:
      - "5000"
    tty: true

