version: "3"
services:
  burninup-frontend:
    image: caitlinlien/burninup:frontend-0.1
    environment:
      PORT: 3000
    ports:
      - 3000:3000
    expose:
      - "3000"
    tty: true
    volumes:
      - .:/cs373-sustainability/frontend

  burninup-backend:
    image: caitlinlien/burninup:backend-0.3
    environment:
      PORT: 5000
    ports:
      - 5000:5000
    expose:
      - "5000"
    tty: true
